plugins {
    id 'java-library'
    id 'org.springframework.boot' version '3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'checkstyle'
}

group = 'com.alkl1m'
version = '0.0.1'
sourceCompatibility = '21'

checkstyle {
    configFile = file('checkstyle.xml')
    toolVersion = '10.12.5'
    ignoreFailures = false
}


repositories {
    mavenCentral()
}

ext {
    lombokVersion = '1.18.30'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

apply from: 'test-tasks.gradle'
apply from: 'dev-tasks.gradle'