plugins {
    id 'java-library'
    id 'org.springframework.boot' version '3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.alkl1m'
version = '0.0.1'
sourceCompatibility = '21'

repositories {
    mavenCentral()
}

ext {
    lombokVersion = '1.18.30'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

test {
    useJUnitPlatform()
}

tasks.register('hello') {
    println 'hello, world'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

task copyResources(type: Copy) {
    from 'src/main/resources'
    into 'build/copy-resources'
    include '**/*.xml'
    exclude '**/temp/*'
    doLast {
        println "Ресурсы скопированы в build/copy-resources"
    }
}

task generateVersionFile {
    def outputFile = file("$DEFAULT_BUILD_DIR_NAME/version.txt")
    outputs.file(outputFile)

    doLast {
        outputFile.parentFile.mkdirs()
        outputFile.text = "Версия проекта: ${project.version}\nСоздано: ${new Date()}"
    }
}

task deepClean(type: Delete) {
    delete 'logs', 'tmp', 'out'
    dependsOn clean
    doLast {
        println "Глубокая очистка выполнена"
    }
}

task projectInfo {
    doLast {
        println "Имя проекта: ${project.name}"
        println "Версия: ${project.version}"
        println "Группа: ${project.group}"
        println "Корневой проект: ${rootProject.name}"
    }
}

task countCodeLines {
    def sources = fileTree('src') {
        include '**/*.java', '**/*.kt', '**/*.groovy'
    }

    doLast {
        def lines = 0
        sources.each { file ->
            file.eachLine { lines++ }
        }

        println "Всего строк кода: $lines"
    }
}

task gitStatus {
    doLast {
        def result = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'status'
            standardOutput = result
        }
        println result.toString()
    }
}

task checkStyle {
    def checkstyleFilePath = "/home/bazingos/IdeaProjects/ipr/counter/checkstyle.xml"
    def checkstyle = new File(checkstyleFilePath)

    doLast {
        if (checkstyle.exists()) {
            def report = new XmlParser().parse(checkstyle)
            def errors = report.file.error.findAll { it.@severity == 'error' }

            if (errors) {
                def errorMessage = "Найдены ошибки стиля: ${errors.size()}\n"
                errorMessage += "Детали ошибок:\n"

                errors.each { error ->
                    errorMessage += " - ${error.@line}: ${error.@message}\n"
                }

                def reportFile = new File("${buildDir}/checkstyle_report.txt")
                reportFile.text = errorMessage

                throw new GradleException(errorMessage)
            } else {
                println "Ошибок стиля не найдено."
            }
        } else {
            println "Файл отчета Checkstyle не найден: ${checkstyleFilePath}"
        }
    }
}

task generateChangelog {
    def changelogFile = new File("${buildDir}/changelog.txt")

    doLast {
        def command = ["git", "log", "--pretty=format:%h - %s (%an, %ar)"]
        def process = command.execute()
        def output = new StringWriter()
        def errorOutput = new StringWriter()
        process.consumeProcessOutput(output, errorOutput)
        process.waitFor()

        if (process.exitValue() == 0) {
            def changelogContent = output.toString()
            changelogFile.text = "Changelog:\n\n${changelogContent}"
            println "Changelog успешно сгенерирован: ${changelogFile.absolutePath}"
        } else {
            println "Не удалось получить коммиты: ${errorOutput.toString()}"
        }
    }
}